version: '3.9'

services:
  mongodb:
    image: 'mongodb/mongodb-community-server:6.0.8-ubi8'
    container_name: 'mongodb'
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGODB_DATA_DIR=/data/db
    volumes:
      - mongodb_data:/data/db
    env_file:
      - "${ENV_FILE:-.env}"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - default

  backend:
    container_name: 'URL_Monitor_API'
    build:
      dockerfile: Dockerfile
      context: .
      target: "${NODE_ENV:-production}"
    ports:
      - "8080:${PORT:-8080}"
    env_file:
      - "${ENV_FILE:-.env}"
    depends_on:
      - mongodb
    restart: always
    networks:
      - default

volumes:
  mongodb_data:
    driver: local
